var FlatlistData =[
    {
        "key":"1",
        "name":"Dr. Sheraz Ahmad",
        "docname":"i have some important issue gjhg jgjhg hgjhg jhghj hgjhg jhgj  with my abdomen",
        "appointmentDate":"10/10/2019",
        "age":"24 y",
        "weight":"70 kg",
    },
    {
        "key":"2",
        "name":"hello world 2",
        "docname":"Mr. Khan",
        "age":"24 y",
        "appointmentDate":"10/10/2019",
        "weight":"70 kg",
    },
    {
        "key":"3",
        "name":"hello world 3",
        "docname":"Mr. Khan",
        "age":"24 y",
        "appointmentDate":"10/10/2019",
        "weight":"70 kg",
    },
    {
        "key":"4",
        "name":"hello world 4",
        "docname":"Mr. Khan",
        "age":"24 y",
        "appointmentDate":"10/10/2019",
        "weight":"70 kg",
    },
    {
        "key":"5",
        "name":"hello world 5",
        "docname":"Mr. Khan",
        "age":"24 y",
        "appointmentDate":"10/10/2019",
        "weight":"70 kg",
    },
    {
        "key":"6",
        "name":"hello world 6",
        "docname":"Mr. Khan",
        "age":"24 y",
        "appointmentDate":"10/10/2019",
        "weight":"70 kg",
    },
    {
        "key":"7",
        "name":"hello world 7",
        "docname":"Mr. Khan",
        "age":"24 y",
        "appointmentDate":"10/10/2019",
        "weight":"70 kg",
    },
    {
        "key":"8",
        "name":"hello world 8",
        "docname":"Mr. Khan",
        "age":"24 y",
        "appointmentDate":"10/10/2019",
        "weight":"70 kg",
    },
    {
        "key":"9",
        "name":"hello world 9",
        "docname":"Mr. Khan",
        "age":"24 y",
        "appointmentDate":"10/10/2019",
        "weight":"70 kg",
    },
    {
        "key":"10",
        "name":"hello world 10",
        "docname":"Mr. Khan",
        "age":"24 y",
        "appointmentDate":"10/10/2019",
        "weight":"70 kg",
    },
    {
        "key":"11",
        "name":"hello world 11",
        "docname":"Mr. Khan",
        "age":"24 y",
        "appointmentDate":"10/10/2019",
        "weight":"70 kg",
    },
    {
        "key":"12",
        "name":"hello world 12",
        "docname":"Mr. Khan",
        "age":"24 y",
        "appointmentDate":"10/10/2019",
        "weight":"70 kg",
    },
    {
        "key":"13",
        "name":"hello world 13",
        "docname":"Mr. Khan",
        "age":"24 y",
        "appointmentDate":"10/10/2019",
        "weight":"70 kg",
    },
    {
        "key":"14",
        "name":"hello world 14",
        "docname":"Mr. Khan",
        "age":"24 y",
        "appointmentDate":"10/10/2019",
        "weight":"70 kg",
    },
    {
        "key":"15",
        "name":"hello world 15",
        "docname":"Mr. Khan",
        "age":"24 y",
        "appointmentDate":"10/10/2019",
        "weight":"70 kg",
    },
];
module.exports = FlatlistData;